name: Deploy to staging

on:
  push:
    branches:
      - master
  
  workflow_dispatch:

env:
  CR_PAT: ${{ vars.CR_PAT }}

jobs:
  test:
    # Use ubuntu-20.04 or ubuntu-22.04 because newer environments drop support for legacy binaries.
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Clone the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Provision Node.js 12 environment
      - name: Setup Node.js 12
        uses: actions/setup-node@v4
        with:
          node-version: '12'
          cache: 'npm' # Speeds up subsequent workflow runs

      # Step 3: Install precise dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run Angular unit tests headlessly
      - name: Run Angular Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/threedradio/intranet-frontend-angular:testing --build-arg NODE_ENV=development --build-arg NG_ENV=staging
      
    - name: Login to the GitHub Docker registry
      run: echo $CR_PAT | docker login ghcr.io -u threedradio --password-stdin
      
    - name: Push the Docker image to ghcr.io
      run: docker push ghcr.io/threedradio/intranet-frontend-angular:testing
  
  deploy:
    needs: build
    environment: test
    runs-on: ubuntu-latest

    steps:
    - name: Set current date
      run: echo "CURRENT_DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Pull the new Docker image from GitHub and restart the container
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ vars.SSH_PORT }}
        script: |
          echo ${{ vars.CR_PAT }} | docker login ghcr.io -u threedradio --password-stdin
          # chown 10001 /srv/docker/intranet-frontend-angular/keys/server.key
          # chown 10001 /srv/docker/intranet-frontend-angular/certs/server.crt
          docker stop intranet-frontend-angular
          docker container rm intranet-frontend-angular
          docker pull ghcr.io/threedradio/intranet-frontend-angular:testing
          docker run \
            -p 8005:443 \
            --name intranet-frontend-angular \
            -v /srv/docker/intranet-frontend-angular/keys/server.key:/etc/nginx/ssl/ssl.key/server.key:z \
            -v /srv/docker/intranet-frontend-angular/certs/server.crt:/etc/nginx/ssl/ssl.cert/server.crt:z \
            -v /data:/data:z \
            -d \
            -t ghcr.io/threedradio/intranet-frontend-angular:testing
