name: Pull request checks

on:
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  pull-request-checks:
    # Use ubuntu-20.04 or ubuntu-22.04 because newer environments drop support for legacy binaries.
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Clone the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Provision Node.js 16 environment
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm" # Speeds up subsequent workflow runs

      # Step 3: Install precise dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Linting
      - name: Run Angular Lint with reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          eslint_flags: "src/"

      - name: Run Prettier with reviewdog
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          filter_mode: added # Only checks lines changed/added in the PR

      # Step 5: Run Angular unit tests headlessly
      - name: Run Angular Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadlessCI
